package com.carparking.core_entity;

public enum CriteriaOperatorE {
	EQUAL, EQUAL_IGNORE_CASE, NOT_EQUAL, IS, IS_NOT, IS_NULL, IS_NOT_NULL, IS_EMPTY, IS_NOT_EMPTY, LIKE,
	LIKE_IGNORE_CASE, GREATER_THAN, GREATER_THAN_OR_EQUAL, LESS_THAN, LESS_THAN_OR_EQUAL, BETWEEN, IN, NOT_IN,
	AND_MULTIPLES, OR_MULTIPLES
}
